name = "shrill-waterfall-93af"
type = "javascript"
account_id = "97afc6815240a28494592018118777f4"

# KV Namespace Binding
kv_namespaces = [
  { binding = "sunny", id = "faae4a5635e644359b51c4ee75151373", preview_id = "faae4a5635e644359b51c4ee75151373" }
]

# Define environment-specific variables for production
[env.production]
name = "sunny-pro"
zone_id = "62d81413ea1d7a79d7db4955960ea09e"
route = "sunny.sirenwatcher.dev/*"

# Environment variables for production
vars = {
  CLOUDFLARE_API_TOKEN = "So9029swrq67z_NvW61W3MYzyyUJrYjTH-IjMiiF"
  SUPABASE_URL = "https://tpogqybedqrbsgjoawxe.supabase.co"
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwb2dxeWJlZHFyYnNnam9hd3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk4ODA2NTEsImV4cCI6MjAxNTQ1NjY1MX0.F3XBYJ-V5_KoXVXKZ0sqgajSzfwPR5Oy1uerUp3bLjA"
  DB_PASSWORD = "HomewardBound1234#"
}

# Define environment-specific variables for development
[env.development]
name = "sunny-dev"
zone_id = "62d81413ea1d7a79d7db4955960ea09e"
route = "sunny.sirenwatcher.dev/*"

# Environment variables for development
vars = {
  CLOUDFLARE_API_TOKEN = "So9029swrq67z_NvW61W3MYzyyUJrYjTH-IjMiiF"
  SUPABASE_URL = "https://tpogqybedqrbsgjoawxe.supabase.co",
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwb2dxeWJlZHFyYnNnam9hd3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk4ODA2NTEsImV4cCI6MjAxNTQ1NjY1MX0.F3XBYJ-V5_KoXVXKZ0sqgajSzfwPR5Oy1uerUp3bLjA"
}
